# Generated by Django 2.1.7 on 2019-03-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('neighborhood', models.CharField(max_length=30)),
                ('room_type', models.CharField(choices=[('Entire Home', 'E'), ('Private Room', 'P'), ('Shared Space', 'S')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('neighborhood', models.CharField(max_length=30)),
                ('room_type', models.CharField(choices=[('Entire Home', 'E'), ('Private Room', 'P'), ('Shared Space', 'S')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
