# Generated by Django 2.1.7 on 2019-03-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbtech', '0005_auto_20190323_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
