# Generated by Django 2.1.7 on 2019-03-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbtech', '0006_auto_20190323_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_preference', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=30)),
                ('lower_price_range', models.DecimalField(decimal_places=2, max_digits=6)),
                ('upper_price_range', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
